/**
 * Nutrition data for all 27 food classes
 * Source: TKPI 2017 (Tabel Komposisi Pangan Indonesia)
 * Values are per 100 gram
 */
const nutritionData = {
  Anggur: {
    nama_pangan: "Anggur segar",
    energi_kkal: 69,
    protein_g: 0.7,
    lemak_g: 0.2,
    karbohidrat_g: 17.3,
    serat_g: 0.9,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  Apel: {
    nama_pangan: "Apel merah segar",
    energi_kkal: 58,
    protein_g: 0.3,
    lemak_g: 0.4,
    karbohidrat_g: 14.9,
    serat_g: 2.6,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  "Ayam Goreng": {
    nama_pangan: "Ayam goreng",
    energi_kkal: 298,
    protein_g: 27.0,
    lemak_g: 20.0,
    karbohidrat_g: 2.0,
    serat_g: 0.0,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  Daging_sapi: {
    nama_pangan: "Daging sapi has",
    energi_kkal: 207,
    protein_g: 18.8,
    lemak_g: 14.0,
    karbohidrat_g: 0.0,
    serat_g: 0.0,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  Ikan: {
    nama_pangan: "Ikan segar (rata-rata)",
    energi_kkal: 113,
    protein_g: 20.0,
    lemak_g: 3.2,
    karbohidrat_g: 0.0,
    serat_g: 0.0,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  Jeruk: {
    nama_pangan: "Jeruk manis segar",
    energi_kkal: 45,
    protein_g: 0.9,
    lemak_g: 0.2,
    karbohidrat_g: 11.2,
    serat_g: 0.4,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  Kelengkeng: {
    nama_pangan: "Kelengkeng segar",
    energi_kkal: 60,
    protein_g: 1.0,
    lemak_g: 0.1,
    karbohidrat_g: 15.1,
    serat_g: 1.1,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  Kentang: {
    nama_pangan: "Kentang rebus",
    energi_kkal: 62,
    protein_g: 2.1,
    lemak_g: 0.1,
    karbohidrat_g: 13.5,
    serat_g: 1.8,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  Kurma: {
    nama_pangan: "Kurma kering",
    energi_kkal: 284,
    protein_g: 2.5,
    lemak_g: 0.4,
    karbohidrat_g: 75.0,
    serat_g: 6.7,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  Leci: {
    nama_pangan: "Leci segar",
    energi_kkal: 66,
    protein_g: 0.8,
    lemak_g: 0.4,
    karbohidrat_g: 16.5,
    serat_g: 1.3,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  Mangga: {
    nama_pangan: "Mangga segar",
    energi_kkal: 65,
    protein_g: 0.7,
    lemak_g: 0.2,
    karbohidrat_g: 16.7,
    serat_g: 1.6,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  Manggis: {
    nama_pangan: "Manggis segar",
    energi_kkal: 63,
    protein_g: 0.6,
    lemak_g: 0.6,
    karbohidrat_g: 15.6,
    serat_g: 1.8,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  Melon: {
    nama_pangan: "Melon segar",
    energi_kkal: 34,
    protein_g: 0.8,
    lemak_g: 0.2,
    karbohidrat_g: 8.2,
    serat_g: 0.9,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  Mie: {
    nama_pangan: "Mie instan goreng",
    energi_kkal: 458,
    protein_g: 7.9,
    lemak_g: 19.7,
    karbohidrat_g: 63.6,
    serat_g: 0.9,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  Nasi: {
    nama_pangan: "Nasi putih",
    energi_kkal: 180,
    protein_g: 3.0,
    lemak_g: 0.3,
    karbohidrat_g: 39.8,
    serat_g: 0.2,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  Pisang: {
    nama_pangan: "Pisang ambon",
    energi_kkal: 89,
    protein_g: 1.2,
    lemak_g: 0.2,
    karbohidrat_g: 22.8,
    serat_g: 2.6,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  Rambutan: {
    nama_pangan: "Rambutan segar",
    energi_kkal: 69,
    protein_g: 0.9,
    lemak_g: 0.3,
    karbohidrat_g: 16.5,
    serat_g: 0.9,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  Roti: {
    nama_pangan: "Roti tawar putih",
    energi_kkal: 248,
    protein_g: 8.0,
    lemak_g: 3.2,
    karbohidrat_g: 46.1,
    serat_g: 2.7,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  Sayur: {
    nama_pangan: "Sayur campuran",
    energi_kkal: 35,
    protein_g: 2.2,
    lemak_g: 0.3,
    karbohidrat_g: 6.4,
    serat_g: 2.0,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  Semangka: {
    nama_pangan: "Semangka merah",
    energi_kkal: 28,
    protein_g: 0.6,
    lemak_g: 0.1,
    karbohidrat_g: 6.9,
    serat_g: 0.4,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  Stroberi: {
    nama_pangan: "Stroberi segar",
    energi_kkal: 32,
    protein_g: 0.7,
    lemak_g: 0.3,
    karbohidrat_g: 7.7,
    serat_g: 2.0,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  Susu: {
    nama_pangan: "Susu sapi segar",
    energi_kkal: 61,
    protein_g: 3.2,
    lemak_g: 3.5,
    karbohidrat_g: 4.3,
    serat_g: 0.0,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  Tahu: {
    nama_pangan: "Tahu goreng",
    energi_kkal: 115,
    protein_g: 7.8,
    lemak_g: 4.6,
    karbohidrat_g: 1.6,
    serat_g: 0.1,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  "Telur Goreng": {
    nama_pangan: "Telur ayam goreng",
    energi_kkal: 196,
    protein_g: 13.6,
    lemak_g: 15.3,
    karbohidrat_g: 0.8,
    serat_g: 0.0,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  "Telur Rebus": {
    nama_pangan: "Telur ayam rebus",
    energi_kkal: 154,
    protein_g: 12.6,
    lemak_g: 10.6,
    karbohidrat_g: 1.1,
    serat_g: 0.0,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  Tempe: {
    nama_pangan: "Tempe goreng",
    energi_kkal: 225,
    protein_g: 18.3,
    lemak_g: 13.5,
    karbohidrat_g: 9.9,
    serat_g: 1.4,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
  Udang: {
    nama_pangan: "Udang segar",
    energi_kkal: 91,
    protein_g: 21.0,
    lemak_g: 0.5,
    karbohidrat_g: 0.1,
    serat_g: 0.0,
    porsi_acuan: "100 gram",
    sumber: "TKPI 2017",
  },
};

export default nutritionData;
